-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP FUNCTION IF EXISTS public.search_courses(keyword text);

CREATE OR REPLACE FUNCTION public.search_courses(IN keyword text)
    RETURNS SETOF courses
    LANGUAGE 'sql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100    ROWS 1000 
    
AS $BODY$
select 
  *
from 
  courses
where
name % keyword or code % keyword
order by 
similarity(code, keyword) desc, similarity(name, keyword) desc
limit 100
$BODY$;
