-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Extension: fuzzystrmatch

-- DROP EXTENSION fuzzystrmatch;

CREATE EXTENSION IF NOT EXISTS fuzzystrmatch
    SCHEMA extensions
    VERSION "1.1";

CREATE OR REPLACE FUNCTION public.search_courses(
	keyword text)
    RETURNS TABLE(name text, code text, code_score real, name_score real) 
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
select 
  name, code, similarity(name, keyword) as name_score, similarity(code, keyword) as code_score
from 
  courses
where
  code % keyword or name % keyword
order by code_score desc, name_score desc
limit 100
$BODY$;

ALTER FUNCTION public.search_courses(text)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.search_courses(text) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.search_courses(text) TO anon;

GRANT EXECUTE ON FUNCTION public.search_courses(text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.search_courses(text) TO postgres;

GRANT EXECUTE ON FUNCTION public.search_courses(text) TO service_role;
