name: CI
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn
      - name: Install playwright browsers for e2e tests
        run: npx playwright install --with-deps
      - run: yarn test
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
