name: CI
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: yarn
      - run: yarn test
      - name: Upload to codecov
        uses: codecov/codecov-action@v3