name: CI
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls
      - run: ls ../
      - run: yarn
      - run: yarn test


  
